### ISSUE TITLE
Backtest feature

### ISSUE THREAD

**Issue by SergioSV96** [garethdmm/gryphon#21]
It would be great to be able to test your strategies with past data on the selected exchanges.

**Comment by garethdmm** [comment]
This is an commonly requested feature, so I'm sure we'll add it in the future!

**Comment by Gabri** [comment]
It's seems to me a ...quite basic feature to rely on this framwork. Ok, it seems a nice project, I develop the strategy ..and then? Testing with live data? Ok, I go further (this was my thought and I think the same for others). For me it should be at priority 1

**Comment by milescui** [comment]
I also need the backtest feature very much.

**Comment by deandreee** [comment]
Has anyone been able to build this? Seems like a must have to test this first.
How about running on testnet? Has anyone had success with that?
