### ISSUE TITLE
Forex:Could not establish redis exchange rate.

### ISSUE THREAD

**Issue by asmodehn** [garethdmm/gryphon#34]
I recently noticed : `INFO:gryphon.lib.forex:Could not establish redis exchange rate.` in my log.

I previously did setup my OXR account, along with a redis DB, and specified that in my configuration as explained in the documentation, since I mostly use EUR as price currency.

What are my options to investigate / debug more, only on this part, without involving a whole strategy run if possible ?

Thanks a lot !

**Comment by garethdmm** [comment]
This message just happens when gryphon is running without GDS, otherwise it's innocuous. If you are using GDS and you see this it might indicate an issue, otherwise you can safely ignore it.

**Comment by asmodehn** [comment]
Ok, thanks for the information. I don't plan to have a GDS anytime soon, so I guess I ll close this then.
