### ISSUE TITLE
The homepage readme "gryphon-exe" is a typo?

### ISSUE THREAD

**Issue by bnfan** [garethdmm/gryphon#51]
"Copy this code into a python file named 'arbitrage.py' in the same directory as your .env file, and you can run it in test mode with gryphon-exe strategy arbitrage."

The command "gryphon-exe strategy arbitrage" should be

"gryphon-exec strategy arbitrage"?

<img width="1055" alt="Screen Shot 2019-07-10 at 3 02 34 PM" src="https://user-images.githubusercontent.com/3311963/60947760-fb7d8180-a323-11e9-89f6-3de0052b9031.png">

**Comment by garethdmm** [comment]
That does in fact look like a typo!

**Comment by garethdmm** [comment]
Fixed in #53
