### ISSUE TITLE
Running [strat_name].py leads to .config file not being found. Original fix did not resolve this

### ISSUE THREAD

**Issue by matteosantama** [garethdmm/gryphon#63]
I believe the fix left this part aside : 
https://github.com/garethdmm/gryphon/blob/master/gryphon/execution/lib/config_helper.py#L96
Which means the configuration file should be named with "strat_name.py.conf" currently, and that is probably not intended

How do we want to handle this? If we're not planning more changes in the original strategy parser, we could simply add a few more if statements. 

_Originally posted by @asmodehn in https://github.com/garethdmm/gryphon/issues/30#issuecomment-508505582_

**Comment by garethdmm** [comment]
Can you verify this is fixed for you by #64 ?

**Comment by garethdmm** [comment]
Closing this because it was fixed in #64.

**Comment by garethdmm** [comment]
Fixed #64 .
