### ISSUE TITLE
Slack invite link is down

### ISSUE THREAD

**Issue by tdudz** [garethdmm/gryphon#76]
It says the invite link is expired when trying to join

**Comment by teretz** [comment]
same here

**Comment by garethdmm** [comment]
This should be fixed now. @teretz @tdudz can you verify?

**Comment by tdudz** [comment]
@garethdmm doesn't seem to work using the link from the readme in the repo. still says it is no longer active

**Comment by garethdmm** [comment]
@tdudz oh gotcha, I thought you meant the gryponframework.org website.

**Comment by garethdmm** [comment]
@tdudz fixed in the readme.

**Comment by tdudz** [comment]
fixed, closing
